### ISSUE TITLE
Can't create the library with newest source

### ISSUE THREAD

**Issue by chinhnd** [saltyrtc/saltyrtc-task-relayed-data-rs#28]
Dear all

I clone the sources, goto ffi and run following the commands

_$ cargo build --release
$ cargo install -f cargo-lipo
$ rustup target add aarch64-apple-ios x86_64-apple-ios
$ cargo lipo --release_

I got this error at last line: _$ cargo lipo --release_
**[ERROR cargo_lipo] No library target found for "saltyrtc-task-relayed-data"**

**My system:**
Xcode 14.2
Mac OS Ventura 13.3.1

Please help to check.

Thank you

**Comment by threema-danilo** [comment]
Hi, it's possible that the build with cargo-lipo is broken, we don't actually build fat binaries anymore.

Instead, we build a binary for each architecture separately, see https://github.com/threema-ch/threema-ios/blob/main/scripts/build-rust.sh and the invocations in https://raw.githubusercontent.com/threema-ch/threema-ios/main/Threema.xcodeproj/project.pbxproj.
